### ISSUE TITLE
[question] Can we upload dataset to fate flow server through fate-operator?

### ISSUE THREAD

**Issue by Guo-Yunzhe** [kubeflow/fate-operator#25]
As I seen in fate-operator proposal, a FATE-Operator is used to 

- manage a FATE Cluster
- submit a FML job to FATE
 
The readme.md only contains a secure add example, I'm wondering that if we want to execute an FML job with additional dataset, can we upload the dataset through .yaml ? Or we can only upload it in KubeFATE, then submit FML job using fate-operator?

Thank you!

**Comment by LaynePeng** [comment]
@Guo-Yunzhe The data can be uploaded with the "yaml" file with KubeFATE as a "JOB". You can find more examples from: https://github.com/FederatedAI/FATE/tree/master/examples especially from https://github.com/FederatedAI/FATE/tree/master/examples/federatedml-1.x-examples , where contains common ML algorithms. Because the uploading also required encryptions and shading, we cannot upload directly in KubeFATE, and located in a cluster.

**Comment by Guo-Yunzhe** [comment]
@LaynePeng Thank you for your reply, but I'm still a little confused about the upload job.

How should I send the data file (for example a csv file) into a KubeFate container?

Can you kindly show an example .yaml to upload data to KubeFATE ?

When I put upload.conf  in the field **modulesConf** , I'm not sure the content in filed **pipeline**.

Thank you.
Yunzhe

**Comment by Guo-Yunzhe** [comment]
Thank you!
